freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script: |
    mount -t fdescfs fdescfs /dev/fd
    pkg install -y bash git gmake
    ln -s ../usr/local/bin/bash /bin/bash
    pw groupadd -n users
    pw useradd -n user -g users -s /bin/sh -m
    git clone . ~user/bfs
    chown -R user:users ~user/bfs
  test_script: |
    su user -c "gmake -C ~/bfs check"
