language: c

script: make check

addons:
  apt:
    packages:
      - acl-dev
      - libcap-dev

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc

    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env:
        - CFLAGS="-m32 -g -Wall"
      addons:
        apt:
          packages:
            - gcc-multilib
            - acl-dev:i386
            - libcap-dev:i386

    - os: linux
      dist: trusty
      sudo: false
      compiler: clang

    - os: osx
      compiler: clang
