language: c

dist: focal
virt: lxd

script: make distcheck

addons:
  apt:
    packages: &packages
      - acl
      - libacl1-dev
      - attr
      - libattr1-dev
      - libcap2-bin
      - libcap-dev

jobs:
  include:
    - os: linux
      arch: amd64
      env: &linux_env
        - TMPDIR=/var/ramfs
      addons:
        apt:
          packages:
            - *packages
            - gcc-multilib
            - libcap2:i386
            - libacl1:i386
            - libattr1:i386
      before_script:
        # Ubuntu doesn't let you install the -dev packages for both amd64 and
        # i386 at once, so we make our own symlinks to fix -m32 -lacl -lcap
        - sudo ln -s libacl.so.1 /lib/i386-linux-gnu/libacl.so
        - sudo ln -s libattr.so.1 /lib/i386-linux-gnu/libattr.so
        - sudo ln -s libcap.so.2 /lib/i386-linux-gnu/libcap.so

    - os: linux
      arch: ppc64le
      env: *linux_env

    - os: osx

    - os: freebsd
      before_script:
        - sudo mount -t fdescfs fdescfs /dev/fd
        - sudo ln -s ../usr/local/bin/bash /bin/bash
      script: gmake distcheck
