language: c

dist: focal
virt: lxd
group: edge

script: make -j$TRAVIS_NUMCORES distcheck

addons:
  apt:
    packages:
      - acl
      - libacl1-dev
      - attr
      - libattr1-dev
      - libcap2-bin
      - libcap-dev

jobs:
  include:
    - os: linux
      arch: amd64
      env: &linux_env
        - TMPDIR=/var/ramfs
      before_script:
        # Work around for https://salsa.debian.org/apt-team/apt/-/commit/998a17d7e6f834c341f198ca5b6df2f27e18df38
        - sudo apt-get -y -o APT::Immediate-Configure=false install gcc-multilib libcap2:i386 libacl1:i386 libattr1:i386
        # Ubuntu doesn't let you install the -dev packages for both amd64 and
        # i386 at once, so we make our own symlinks to fix -m32 -lacl -lattr -lcap
        - sudo ln -s libacl.so.1 /lib/i386-linux-gnu/libacl.so
        - sudo ln -s libattr.so.1 /lib/i386-linux-gnu/libattr.so
        - sudo ln -s libcap.so.2 /lib/i386-linux-gnu/libcap.so

    - os: linux
      arch: ppc64le
      env: *linux_env

    - os: osx

    - os: freebsd
      before_script:
        - sudo mount -t fdescfs fdescfs /dev/fd
        - sudo ln -s ../usr/local/bin/bash /bin/bash
      script: gmake -j2 distcheck
