language: c

script: make distcheck

addons:
  apt:
    packages:
      - gcc-multilib
      - libacl1-dev
      - libacl1:i386
      - libcap-dev
      - libcap2:i386

matrix:
  include:
    - os: linux
      dist: xenial
      before_script:
        # Ubuntu doesn't let you install the -dev packages for both amd64 and
        # i386 at once, so we make our own symlinks to fix -m32 -lacl -lcap
        - sudo ln -s libacl.so.1 /lib/i386-linux-gnu/libacl.so
        - sudo ln -s libcap.so.2 /lib/i386-linux-gnu/libcap.so

    - os: osx
